version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: claims_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: claims_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5095:5432"

  backend:
    build: ./Backend
    container_name: claims_backend
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin123
      PGDATABASE: claims_db
      PGHOST: postgres
      PGPORT: 5432
    ports:
      - "3095:3095"

  employee-claims:
    build: ./Employee-claims
    container_name: claims_employee_ui
    ports:
      - "8159:80"
    depends_on:
      - backend

  hr-claims:
    build: ./HR-claims
    container_name: claims_hr_ui
    ports:
      - "8160:80"
    depends_on:
      - backend

volumes:
  postgres_data:

